/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nrouge_sudoku_solver_impl_JNISolverHelper */

#ifndef _Included_com_nrouge_sudoku_solver_impl_JNISolverHelper
#define _Included_com_nrouge_sudoku_solver_impl_JNISolverHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nrouge_sudoku_solver_impl_JNISolverHelper
 * Method:    solve
 * Signature: (Lcom/nrouge/sudoku/model/Grille;I)V
 */
JNIEXPORT void JNICALL Java_com_nrouge_sudoku_solver_impl_JNISolverHelper_solve
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
